#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#


          OBJ_OPTIMIZE = paw_utils.o integrate.o io_utils.o chkerr.o double_factorial.o bessel_transform.o \
                paw_gauss_weights.o paw_spher_grid.o

          HEADERS = bessel_transform.fh integrate.fh paw_utils.fh paw_params.fh


      LIBRARY =	libpaw.a

   USES_BLAS = integrate.F

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












