#
# $Id: GNUmakefile 21176 2011-10-10 06:35:49Z d3y133 $
#

OBJ_OPTIMIZE =  string.o string_input.o

LIBRARY=liboptim.a

HEADERS=

USES_BLAS= 

include ../../config/makefile.h

include ../../config/makelib.h

showobj:
	echo "obj $(OBJ) "
	echo "obj_opt $(OBJ_OPTIMIZE)"
