#
# $Id: GNUmakefile 20222 2011-04-20 02:00:28Z jhammond $
#

 OBJ_OPTIMIZE =  qmd_start.o qmd_main.o 

LIBRARY=libqmd.a

HEADERS=

USES_BLAS=

include ../config/makefile.h

include ../config/makelib.h

showobj:
	echo "obj $(OBJ) "
	echo "obj_opt $(OBJ_OPTIMIZE)"
